name: hmyLobby
version: "1.0"
main: de.haaremy.hmylobby.HmyLobby
api-version: 1.19
depend: [LuckPerms]
description: Ein Plugin von @Haaremy zur Verwaltung eines Lobby-Servers.
author: Haaremy
website: https://haaremy.de
commands:
  server:
    description: "Teleportiert dich zum gewählten Server."
    usage: "/hmy server <name>"
    permission: hmy.server.<name>
  hmy:
    description: "Hauptbefehl des Haaremy-Plugins."
    usage: "/hmy <language|ballon> [args...]"
  lobbygame:
    description: "Erstellt und verwaltet Lobby-Minispiele."
    usage: "/lobbygame <create> <tiktaktoe> <name> <feld-id>"
    permission: hmy.lobby.gamecreator
permissions:
  hmy.lobby.message.none:
    description: Deaktiviert die Willkommensnachricht beim Betreten der Lobby.
    default: false
  hmy.lobby.sound.none:
    description: Deaktiviert die Sounds beim Betreten der Lobby.
    default: false
  hmy.lobby.particle.none:
    description: Deaktiviert die Partikel beim Betreten der Lobby.
    default: false
  hmy.lobby.inventory.edit:
    description: Erlaubt das editieren der Inventory Slots.
    default: false
  hmy.lobby.gamecreator:
    description: Erlaubt das Erstellen von Lobby-Minispielen.
    default: op
  hmy.lobby.rocket:
    description: Erlaubt die Nutzung des Sprung Boosts.
    default: true
  hmy.lobby.visibility:
    description: Erlaubt das Ausblenden anderer Spieler.
    default: true
  hmy.lobby.selector:
    description: Erlaubt die Nutzung des Navigators.
    default: true
  hmy.lobby.speed:
    description: Erlaubt das Ändern der Laufgeschwindigkeit.
    default: true
  hmy.lobby.tp.*:
    description: Erlaubt alle Lobby-Teleportpunkte (Kompass im Navigator).
    default: true
  hmy.lobby.balloon.use:
    description: Erlaubt das Mitfahren auf Ballons und Fahrstühlen.
    default: true
  hmy.lobby.balloon.admin:
    description: Erlaubt das Erstellen und Verwalten von Ballon-Routen und Fahrstühlen.
    default: op
